# Generated by Django 5.1.1 on 2026-09-10 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, help_text='Primary identifier. Must be a valid Rwandan phone number in E.164 format.', max_length=20, unique=True, verbose_name='Phone Number')),
                ('email', models.EmailField(blank=True, help_text='Optional. Must be unique when provided.', max_length=254, null=True, unique=True, verbose_name='Email Address')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('role', models.CharField(choices=[('STUDENT', 'Student'), ('GUEST', 'Guest'), ('TUTOR', 'Tutor / Facilitator'), ('ENTERPRISE_ADMIN', 'Enterprise Admin'), ('BOARD_REVIEWER', 'Board Reviewer'), ('TRAINING_ADMIN', 'Training Administrator'), ('SYSTEM_ADMIN', 'System Admin')], db_index=True, default='GUEST', max_length=20, verbose_name='Role')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('PENDING_VERIFICATION', 'Pending Phone Verification'), ('SUSPENDED', 'Suspended'), ('DEACTIVATED', 'Deactivated')], db_index=True, default='PENDING_VERIFICATION', max_length=30, verbose_name='Account Status')),
                ('student_id', models.CharField(blank=True, db_index=True, help_text='Auto-generated upon enrollment confirmation. Format: SIFO-STU-YYYY-XXXX', max_length=30, null=True, unique=True, verbose_name='Student ID')),
                ('school_name', models.CharField(blank=True, default='', help_text='Only populated for ENTERPRISE_ADMIN accounts.', max_length=200, verbose_name='Driving School Name')),
                ('station_quota', models.PositiveSmallIntegerField(default=1, help_text='Maximum concurrent exam sessions for this enterprise account.', verbose_name='Station Quota')),
                ('national_id_encrypted', models.TextField(blank=True, default='', help_text='AES-256 encrypted 16-digit National Identification Number (Indangamuntu). Never stored in plaintext per Rwanda Law No 058/2021.', verbose_name='National ID (Encrypted)')),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='profiles/photos/%Y/%m/', verbose_name='Profile Photo')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('terms_of_service_accepted', models.BooleanField(default=False, help_text='Must be True before a user can access any platform feature. Required at the point of registration for both guests and students.', verbose_name='Terms of Service Accepted')),
                ('terms_of_service_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Terms of Service Accepted At')),
                ('privacy_policy_accepted', models.BooleanField(default=False, help_text='Required before collecting any PII or biometrics (Art. 6 & 17). Students accept at registration; guests are prompted when needed.', verbose_name='Privacy Policy Accepted')),
                ('privacy_policy_accepted_at', models.DateTimeField(blank=True, null=True, verbose_name='Privacy Policy Accepted At')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into the Django admin site.', verbose_name='Staff Status')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active')),
                ('last_login_ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='Last Login IP')),
                ('assigned_tutor', models.ForeignKey(blank=True, limit_choices_to={'role': 'TUTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutoring_students', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Tutor')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(db_index=True, max_length=20, verbose_name='Phone Number')),
                ('otp_hash', models.CharField(help_text='SHA-256 hash of the OTP code. Never store the raw code.', max_length=128, verbose_name='OTP Hash')),
                ('purpose', models.CharField(choices=[('REGISTRATION', 'Account Registration'), ('LOGIN', 'Login Verification'), ('PHONE_CHANGE', 'Phone Number Change'), ('PASSWORD_RESET', 'Password Reset'), ('IREMBO_BOOKING', 'Irembo Booking Confirmation')], default='REGISTRATION', max_length=30, verbose_name='Purpose')),
                ('expires_at', models.DateTimeField(verbose_name='Expires At')),
                ('is_used', models.BooleanField(default=False, verbose_name='Used')),
                ('attempt_count', models.PositiveSmallIntegerField(default=0, help_text='Number of failed verification attempts for this code.', verbose_name='Attempt Count')),
            ],
            options={
                'verbose_name': 'OTP Verification',
                'verbose_name_plural': 'OTP Verifications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['phone_number', 'purpose', 'is_used'], name='accounts_ot_phone_n_57b6b1_idx')],
            },
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('preferred_language', models.CharField(choices=[('en', 'English'), ('rw', 'Kinyarwanda')], default='en', max_length=10, verbose_name='Preferred Language')),
                ('license_category', models.CharField(choices=[('A', 'Category A — Motorcycles'), ('B', 'Category B — Light Motor Vehicles'), ('C', 'Category C — Heavy Motor Vehicles'), ('D', 'Category D — Passenger Buses'), ('E', 'Category E — Articulated Vehicles'), ('F', 'Category F — Agricultural Vehicles')], default='B', max_length=5, verbose_name='License Category')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='Enrollment Date')),
                ('current_streak_days', models.PositiveIntegerField(default=0, verbose_name='Current Streak (Days)')),
                ('longest_streak_days', models.PositiveIntegerField(default=0, verbose_name='Longest Streak (Days)')),
                ('last_activity_date', models.DateField(blank=True, null=True, verbose_name='Last Activity Date')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'STUDENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Student Profile',
                'verbose_name_plural': 'Student Profiles',
            },
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['role', 'status'], name='accounts_us_role_9fc6ca_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['student_id'], name='accounts_us_student_0a3672_idx'),
        ),
    ]
