# Generated by Django 5.1.1 on 2026-09-17 19:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCommissionConfig',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('BOOKING', 'Driving Test Booking Concierge'), ('SUBSCRIPTION', 'Course Subscription'), ('EXAM_PURCHASE', 'Single / Multi Exam Purchase'), ('LEARNING_FEE', 'Tuition / Learning Fee'), ('OTHER', 'Other Facilitated Service')], db_index=True, max_length=30, unique=True, verbose_name='Service Type')),
                ('service_name', models.CharField(max_length=120, verbose_name='Service Display Name')),
                ('default_client_price_rwf', models.PositiveIntegerField(default=2500, help_text='Standard price charged to clients for this service.', verbose_name='Default Client Price (RWF)')),
                ('commission_fee_rwf', models.PositiveIntegerField(default=500, help_text='Flat commission earned by agent per completed service.', verbose_name='Agent Commission Fee (RWF)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Internal Notes')),
            ],
            options={
                'verbose_name': 'Service Commission Config',
                'verbose_name_plural': 'Service Commission Configs',
                'ordering': ['service_name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='created_by_agent',
            field=models.ForeignKey(blank=True, help_text='The Sifo Drive field agent who registered or assisted this client.', limit_choices_to={'role': 'AGENT'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clients_onboarded', to=settings.AUTH_USER_MODEL, verbose_name='Onboarded by Agent'),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('STUDENT', 'Student'), ('GUEST', 'Guest'), ('TUTOR', 'Tutor / Facilitator'), ('ENTERPRISE_ADMIN', 'Enterprise Admin'), ('BOARD_REVIEWER', 'Board Reviewer'), ('TRAINING_ADMIN', 'Training Administrator'), ('AGENT', 'Agent / Sifo Drive Agent'), ('SYSTEM_ADMIN', 'System Admin')], db_index=True, default='GUEST', max_length=20, verbose_name='Role'),
        ),
        migrations.CreateModel(
            name='AgentCommission',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('service_type', models.CharField(choices=[('BOOKING', 'Driving Test Booking Concierge'), ('SUBSCRIPTION', 'Course Subscription'), ('EXAM_PURCHASE', 'Single / Multi Exam Purchase'), ('LEARNING_FEE', 'Tuition / Learning Fee'), ('OTHER', 'Other Facilitated Service')], db_index=True, default='BOOKING', max_length=30, verbose_name='Service Type')),
                ('service_reference', models.CharField(blank=True, default='', help_text='Booking ticket number, payment transaction UUID, or subscription reference.', max_length=100, verbose_name='Service Reference')),
                ('amount_paid_by_client_rwf', models.PositiveIntegerField(default=2500, verbose_name='Amount Paid by Client (RWF)')),
                ('commission_amount_rwf', models.PositiveIntegerField(default=500, verbose_name='Commission Fee Earned (RWF)')),
                ('status', models.CharField(choices=[('ACCRUED', 'Accrued (Pending Monthly Payout)'), ('PAID_OUT', 'Paid Out'), ('CANCELLED', 'Cancelled')], db_index=True, default='ACCRUED', max_length=20, verbose_name='Commission Status')),
                ('paid_out_at', models.DateTimeField(blank=True, null=True, verbose_name='Paid Out At')),
                ('payout_batch_id', models.CharField(blank=True, default='', max_length=50, verbose_name='Payout Batch ID')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Internal Remarks')),
                ('agent', models.ForeignKey(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='commissions_earned', to=settings.AUTH_USER_MODEL, verbose_name='Agent')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='agent_facilitated_services', to=settings.AUTH_USER_MODEL, verbose_name='Client')),
                ('paid_out_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payouts_administered', to=settings.AUTH_USER_MODEL, verbose_name='Settled By Admin')),
            ],
            options={
                'verbose_name': 'Agent Commission Record',
                'verbose_name_plural': 'Agent Commission Records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_code', models.CharField(db_index=True, help_text='Unique identifier (e.g. SIFO-AGT-001).', max_length=30, unique=True, verbose_name='Agent Code')),
                ('business_name', models.CharField(blank=True, default='', help_text="Name of the agent's kiosk, cyber café, or agency location.", max_length=150, verbose_name='Kiosk / Agency Business Name')),
                ('national_id_number', models.CharField(blank=True, default='', max_length=30, verbose_name='National ID Number')),
                ('district', models.CharField(blank=True, default='', max_length=50, verbose_name='District')),
                ('sector', models.CharField(blank=True, default='', max_length=50, verbose_name='Sector')),
                ('total_accrued_rwf', models.PositiveIntegerField(default=0, help_text='All-time commission calculated from client services.', verbose_name='Total Accrued Commissions (RWF)')),
                ('total_paid_out_rwf', models.PositiveIntegerField(default=0, help_text='All-time commission settled and paid to agent by admin.', verbose_name='Total Paid Out (RWF)')),
                ('last_payout_date', models.DateField(blank=True, help_text='Date of the most recent monthly settlement.', null=True, verbose_name='Last Payout Date')),
                ('is_approved', models.BooleanField(default=True, verbose_name='Is Approved')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'AGENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='agent_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Agent Profile',
                'verbose_name_plural': 'Agent Profiles',
                'ordering': ['agent_code'],
            },
        ),
    ]
