# Generated by Django 5.1.1 on 2026-09-30 11:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_servicecommissionconfig_user_created_by_agent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnterpriseProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('school_name', models.CharField(help_text='Official registered driving school name.', max_length=200, verbose_name='Driving School Name')),
                ('registration_number', models.CharField(db_index=True, help_text='Official business and accreditation license number.', max_length=50, unique=True, verbose_name='RDB / MININFRA Registration Number')),
                ('district', models.CharField(default='Kigali', help_text='District where driving school campus is located.', max_length=50, verbose_name='District')),
                ('sector', models.CharField(blank=True, default='', max_length=50, verbose_name='Sector')),
                ('address_line', models.CharField(blank=True, default='', max_length=255, verbose_name='Campus Address')),
                ('contact_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Official Contact Email')),
                ('contact_phone', models.CharField(blank=True, default='', max_length=20, verbose_name='Contact Phone Number')),
                ('concurrent_station_quota', models.PositiveSmallIntegerField(default=20, help_text='Maximum concurrent hardware exam workstations allowed for this school.', verbose_name='Licensed Concurrent Lab Stations')),
                ('is_verified_school', models.BooleanField(default=True, verbose_name='Verified Driving School')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'ENTERPRISE_ADMIN'}, on_delete=django.db.models.deletion.CASCADE, related_name='enterprise_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Enterprise Profile',
                'verbose_name_plural': 'Enterprise Profiles',
                'ordering': ['school_name'],
            },
        ),
        migrations.CreateModel(
            name='ReviewerProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewer_code', models.CharField(db_index=True, help_text='Unique identifier (e.g. SIFO-REV-001).', max_length=30, unique=True, verbose_name='Reviewer Code')),
                ('inspector_badge_number', models.CharField(blank=True, default='', help_text='Official inspection or regulatory authority badge number.', max_length=50, verbose_name='Inspector Badge / License Number')),
                ('accreditation_authority', models.CharField(default='Rwanda National Police / Sifo Board of Examiners', max_length=150, verbose_name='Accreditation Authority')),
                ('total_reviews_completed', models.PositiveIntegerField(default=0, verbose_name='Total Reviews Completed')),
                ('total_certifications_approved', models.PositiveIntegerField(default=0, verbose_name='Total Certifications Approved')),
                ('total_violations_confirmed', models.PositiveIntegerField(default=0, verbose_name='Total Violations Confirmed')),
                ('is_active_reviewer', models.BooleanField(default=True, verbose_name='Is Active Reviewer')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'BOARD_REVIEWER'}, on_delete=django.db.models.deletion.CASCADE, related_name='reviewer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reviewer Profile',
                'verbose_name_plural': 'Reviewer Profiles',
                'ordering': ['reviewer_code'],
            },
        ),
        migrations.CreateModel(
            name='TutorProfile',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('tutor_code', models.CharField(db_index=True, help_text='Unique identifier (e.g. SIFO-TUT-001).', max_length=30, unique=True, verbose_name='Tutor Code')),
                ('title', models.CharField(default='Theory & Practical Driving Instructor', help_text='e.g. Senior Traffic Law Instructor, Category B Specialist', max_length=120, verbose_name='Professional Title')),
                ('bio', models.TextField(blank=True, default='', verbose_name='Instructor Biography')),
                ('specialization_categories', models.JSONField(blank=True, default=list, help_text="List of license categories taught, e.g. ['A', 'B', 'C'].", verbose_name='Specialization License Categories')),
                ('default_meeting_url', models.URLField(blank=True, default='', help_text='Permanent Google Meet link used for recurring live sessions.', max_length=500, verbose_name='Default Google Meet URL')),
                ('is_available_for_tutoring', models.BooleanField(default=True, verbose_name='Available for Tutoring')),
                ('max_student_capacity', models.PositiveIntegerField(default=50, help_text='Maximum concurrent learners assigned to this instructor.', verbose_name='Maximum Student Capacity')),
                ('total_teaching_hours', models.PositiveIntegerField(default=0, verbose_name='Total Teaching Hours')),
                ('rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3, verbose_name='Instructor Rating')),
                ('user', models.OneToOneField(limit_choices_to={'role': 'TUTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tutor Profile',
                'verbose_name_plural': 'Tutor Profiles',
                'ordering': ['tutor_code'],
            },
        ),
    ]
