# Generated by Django 5.1.1 on 2026-10-01 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_enterpriseprofile_reviewerprofile_tutorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='biography',
            field=models.TextField(blank=True, default='', help_text='Short user bio displayed on their Canvas profile.', verbose_name='Biography'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_methods',
            field=models.JSONField(blank=True, default=list, help_text='Additional contact methods (email, secondary phone, linkedin, etc).', verbose_name='Ways to Contact'),
        ),
        migrations.AddField(
            model_name='user',
            name='links',
            field=models.JSONField(blank=True, default=list, help_text='List of external links/portfolios (title and url).', verbose_name='Profile Links'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_enabled',
            field=models.BooleanField(default=False, help_text='Require OTP verification code when logging in.', verbose_name='Two-Factor Authentication Enabled'),
        ),
        migrations.AddField(
            model_name='user',
            name='two_factor_method',
            field=models.CharField(choices=[('phone', 'Phone SMS'), ('email', 'Email')], default='phone', help_text='Channel to receive login OTP (phone or email).', max_length=10, verbose_name='Two-Factor Method'),
        ),
    ]
