# Generated by Django 5.2.17 on 2026-09-10 13:39

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cohort',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('name', models.CharField(max_length=150, verbose_name='Cohort Name')),
                ('code', models.CharField(db_index=True, help_text='Unique identifier, e.g. COHORT-2026-SEP-AM', max_length=50, unique=True, verbose_name='Cohort Code')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('start_date', models.DateField(verbose_name='Start Date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='End Date')),
                ('max_capacity', models.PositiveIntegerField(default=50, verbose_name='Max Capacity')),
                ('is_active', models.BooleanField(db_index=True, default=True, verbose_name='Is Active')),
                ('schedule_description', models.CharField(blank=True, help_text='e.g. Mon, Wed, Fri 09:00 - 11:00 CAT', max_length=255, verbose_name='Schedule Description')),
                ('assigned_tutors', models.ManyToManyField(blank=True, related_name='assigned_cohorts', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Tutors / Teachers')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('students', models.ManyToManyField(blank=True, related_name='enrolled_cohorts', to=settings.AUTH_USER_MODEL, verbose_name='Enrolled Students')),
            ],
            options={
                'verbose_name': 'Cohort',
                'verbose_name_plural': 'Cohorts',
                'ordering': ['-start_date', 'name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LiveClass',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('topic', models.CharField(blank=True, max_length=300, verbose_name='Topic')),
                ('scheduled_date', models.DateField(db_index=True, verbose_name='Scheduled Date')),
                ('start_time', models.TimeField(verbose_name='Start Time')),
                ('end_time', models.TimeField(verbose_name='End Time')),
                ('google_meet_url', models.URLField(help_text='Google Meet conference link for this session', verbose_name='Google Meet URL')),
                ('status', models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('IN_PROGRESS', 'In Progress / Live Now'), ('COMPLETED', 'Completed'), ('RESCHEDULED', 'Rescheduled'), ('CANCELLED', 'Cancelled')], db_index=True, default='SCHEDULED', max_length=25, verbose_name='Status')),
                ('is_published', models.BooleanField(db_index=True, default=False, help_text='Whether the class is visible on student timetables', verbose_name='Is Published')),
                ('notes', models.TextField(blank=True, verbose_name='Session Notes / Syllabus Instructions')),
                ('recording_url', models.URLField(blank=True, help_text='Link to cloud recording (Drive / YouTube Unlisted / CDN)', verbose_name='Recording URL')),
                ('actual_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Actual Started At')),
                ('actual_ended_at', models.DateTimeField(blank=True, null=True, verbose_name='Actual Ended At')),
                ('cohort', models.ForeignKey(blank=True, help_text='Specific student cohort, or blank for platform-wide open class', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='live_classes', to='live_classes.cohort', verbose_name='Assigned Cohort')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_live_classes', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='lms.lesson', verbose_name='Related Lesson')),
                ('module', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='live_classes', to='lms.module', verbose_name='Related Curriculum Module')),
                ('tutor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tutored_classes', to=settings.AUTH_USER_MODEL, verbose_name='Tutor / Teacher')),
            ],
            options={
                'verbose_name': 'Live Class',
                'verbose_name_plural': 'Live Classes',
                'ordering': ['scheduled_date', 'start_time'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassResource',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('title', models.CharField(max_length=200, verbose_name='Resource Title')),
                ('file', models.FileField(blank=True, help_text='PDF slide deck, worksheet, or summary document', null=True, upload_to='live_classes/resources/%Y/%m/', verbose_name='Attached File')),
                ('external_link', models.URLField(blank=True, help_text='Google Drive, Figma, or web resource link', verbose_name='External Link')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_class_resources', to=settings.AUTH_USER_MODEL)),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='live_classes.liveclass', verbose_name='Live Class')),
            ],
            options={
                'verbose_name': 'Class Resource',
                'verbose_name_plural': 'Class Resources',
                'ordering': ['title'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ClassAttendance',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('LATE', 'Late'), ('ABSENT', 'Absent'), ('EXCUSED', 'Excused'), ('WATCHED_RECORDING', 'Watched Recording')], default='PRESENT', max_length=25, verbose_name='Attendance Status')),
                ('joined_at', models.DateTimeField(blank=True, null=True, verbose_name='Joined At')),
                ('minutes_attended', models.PositiveIntegerField(default=0, verbose_name='Minutes Attended')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='Attendance Notes')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('marked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='marked_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Recorded By (Tutor/Admin)')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='class_attendances', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
                ('live_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='live_classes.liveclass', verbose_name='Live Class')),
            ],
            options={
                'verbose_name': 'Class Attendance',
                'verbose_name_plural': 'Class Attendances',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['scheduled_date', 'status'], name='lc_date_status_idx'),
        ),
        migrations.AddIndex(
            model_name='liveclass',
            index=models.Index(fields=['cohort', 'scheduled_date'], name='lc_cohort_date_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['student', 'status'], name='att_student_status_idx'),
        ),
        migrations.AddIndex(
            model_name='classattendance',
            index=models.Index(fields=['live_class', 'status'], name='att_class_status_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='classattendance',
            unique_together={('student', 'live_class')},
        ),
    ]
