# Generated by Django 5.1.1 on 2026-09-13 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0002_alter_cohort_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='description',
            field=models.CharField(blank=True, help_text='Cohort summary (max 165 characters)', max_length=165, verbose_name='Description'),
        ),
    ]
