# Generated by Django 5.1.1 on 2026-10-02 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0003_alter_cohort_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='status',
            field=models.CharField(choices=[('queue', 'Queue'), ('open', 'Open'), ('closed', 'Closed'), ('ended', 'Ended')], db_index=True, default='queue', help_text='queue: waiting in queue, open: default cohort for new registered students, closed: capacity reached or closed by admin, ended: scheduled time reached', max_length=20, verbose_name='Cohort Status'),
        ),
    ]
