# Generated by Django 5.1.1 on 2026-10-02 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('live_classes', '0004_cohort_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='identifier',
            field=models.CharField(blank=True, db_index=True, help_text='3-digit auto-generated identifier, e.g. 001, 002', max_length=10, null=True, unique=True, verbose_name='3-digit Identifier'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='sequence_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Auto-incrementing integer sequence starting from 1', null=True, unique=True, verbose_name='Sequence Number'),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='max_capacity',
            field=models.PositiveIntegerField(default=60, verbose_name='Max Capacity'),
        ),
    ]
