# Generated by Django 5.1.1 on 2026-09-10 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('provider', models.CharField(choices=[('MTN', 'MTN Mobile Money'), ('AIRTEL', 'Airtel Money')], max_length=10, verbose_name='Provider')),
                ('fee_type', models.CharField(choices=[('STUDENT_TUITION', 'Student Tuition Fee'), ('GUEST_EXAM_PASS', 'Guest Exam Single Pass'), ('ENTERPRISE_LICENSE', 'Enterprise Lab License'), ('IREMBO_CONCIERGE', 'Irembo Concierge Fee')], max_length=25, verbose_name='Fee Type')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Amount (RWF)')),
                ('currency', models.CharField(default='RWF', max_length=5, verbose_name='Currency')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Payer Phone')),
                ('status', models.CharField(choices=[('INITIATED', 'Initiated'), ('PENDING', 'Pending MoMo Approval'), ('SUCCESSFUL', 'Successful'), ('FAILED', 'Failed'), ('REFUNDED', 'Refunded')], db_index=True, default='INITIATED', max_length=15, verbose_name='Status')),
                ('provider_transaction_id', models.CharField(blank=True, max_length=200, null=True, unique=True, verbose_name='Provider TX ID')),
                ('idempotency_key', models.UUIDField(unique=True, verbose_name='Idempotency Key')),
                ('webhook_payload', models.JSONField(blank=True, null=True, verbose_name='Webhook Payload')),
                ('failed_reason', models.CharField(blank=True, max_length=500, verbose_name='Failure Reason')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('payer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
