# Generated by Django 5.1.1 on 2026-09-12 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='explanation_kinyarwanda',
            field=models.TextField(blank=True, help_text="Ibisobanuro mu Kinyarwanda by'impamvu igisubizo ari cyo cy'ukuri.", verbose_name='Explanation (Kinyarwanda)'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='Road sign or intersection diagram associated with this question.', null=True, upload_to='lms/questions/images/', verbose_name='Diagram / Image'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_a_kinyarwanda',
            field=models.CharField(blank=True, max_length=500, verbose_name='Option A (Kinyarwanda)'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b_kinyarwanda',
            field=models.CharField(blank=True, max_length=500, verbose_name='Option B (Kinyarwanda)'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c_kinyarwanda',
            field=models.CharField(blank=True, max_length=500, verbose_name='Option C (Kinyarwanda)'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d_kinyarwanda',
            field=models.CharField(blank=True, max_length=500, verbose_name='Option D (Kinyarwanda)'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='question_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, help_text='Official Rwanda Highway Code question reference number (1-433).', null=True, verbose_name='Question Number'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='explanation',
            field=models.TextField(blank=True, help_text='Shown after the student answers. Explains why the answer is correct.', verbose_name='Explanation (English)'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_a',
            field=models.CharField(blank=True, max_length=500, verbose_name='Option A (English)'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_b',
            field=models.CharField(blank=True, max_length=500, verbose_name='Option B (English)'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_c',
            field=models.CharField(blank=True, max_length=500, verbose_name='Option C (English)'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='option_d',
            field=models.CharField(blank=True, max_length=500, verbose_name='Option D (English)'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='question_text',
            field=models.TextField(blank=True, verbose_name='Question (English)'),
        ),
    ]
