# Generated by Django 5.1.1 on 2026-09-12 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0002_quizquestion_explanation_kinyarwanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='option_a_image',
            field=models.ImageField(blank=True, help_text='Image diagram for Option A if this question uses image-based choices.', null=True, upload_to='lms/questions/options/', verbose_name='Option A Image'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_b_image',
            field=models.ImageField(blank=True, help_text='Image diagram for Option B if this question uses image-based choices.', null=True, upload_to='lms/questions/options/', verbose_name='Option B Image'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_c_image',
            field=models.ImageField(blank=True, help_text='Image diagram for Option C if this question uses image-based choices.', null=True, upload_to='lms/questions/options/', verbose_name='Option C Image'),
        ),
        migrations.AddField(
            model_name='quizquestion',
            name='option_d_image',
            field=models.ImageField(blank=True, help_text='Image diagram for Option D if this question uses image-based choices.', null=True, upload_to='lms/questions/options/', verbose_name='Option D Image'),
        ),
        migrations.AlterField(
            model_name='quizquestion',
            name='image',
            field=models.ImageField(blank=True, help_text='Road sign or intersection diagram associated with this question prompt.', null=True, upload_to='lms/questions/images/', verbose_name='Diagram / Image'),
        ),
    ]
