# Generated by Django 5.1.1 on 2026-09-22 12:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_default_curriculum_and_link_courses(apps, schema_editor):
    Curriculum = apps.get_model('lms', 'Curriculum')
    Course = apps.get_model('lms', 'Course')

    courses = Course.objects.filter(curriculum__isnull=True)
    if courses.exists():
        default_curr, _ = Curriculum.objects.get_or_create(
            code='RW-CURR-UNIVERSAL',
            defaults={
                'title': 'Universal Rwanda Driving Theory Curriculum',
                'title_kinyarwanda': "Integanyanyigisho Rusange yo mu Rwanda",
                'description': 'Universal road safety regulations, traffic signs, and driver education curriculum.',
                'description_kinyarwanda': "Integanyanyigisho rusange y'amategeko y'umuhanda, ibyapa n'imyitwarire y'umuyobozi w'ikinyabiziga.",
                'is_published': True,
            }
        )
        courses.update(curriculum=default_curr)


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0003_quizquestion_option_a_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='code',
            field=models.CharField(blank=True, default='', help_text='Course code identifier, e.g. RWT-01.', max_length=50, verbose_name='Code'),
        ),
        migrations.AddField(
            model_name='course',
            name='description_kinyarwanda',
            field=models.TextField(blank=True, default='', verbose_name='Description (Kinyarwanda)'),
        ),
        migrations.AddField(
            model_name='course',
            name='title_kinyarwanda',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Kinyarwanda)'),
        ),
        migrations.CreateModel(
            name='Curriculum',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Controls the display ordering of this record within its parent. Lower values appear first.', verbose_name='Sort Order')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('title_kinyarwanda', models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Kinyarwanda)')),
                ('code', models.CharField(blank=True, help_text='Curriculum identifier, e.g. RW-CURR-UNIVERSAL', max_length=50, null=True, unique=True, verbose_name='Code')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description')),
                ('description_kinyarwanda', models.TextField(blank=True, default='', verbose_name='Description (Kinyarwanda)')),
                ('thumbnail', models.ImageField(blank=True, help_text='Curriculum cover image.', null=True, upload_to='lms/curricula/thumbnails/', verbose_name='Thumbnail')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('published_at', models.DateTimeField(blank=True, null=True, verbose_name='Published At')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_curricula', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_curricula', to=settings.AUTH_USER_MODEL, verbose_name='Published By')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_curricula', to=settings.AUTH_USER_MODEL, verbose_name='Last Updated By')),
            ],
            options={
                'verbose_name': 'Curriculum',
                'verbose_name_plural': 'Curricula',
                'ordering': ['sort_order', '-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=models.ForeignKey(blank=True, help_text='Parent curriculum containing this course.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='lms.curriculum', verbose_name='Curriculum'),
        ),
        migrations.RunPython(create_default_curriculum_and_link_courses, reverse_code=migrations.RunPython.noop),
    ]
