# Generated by Django 5.1.1 on 2026-09-22 16:22

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0004_course_code_course_description_kinyarwanda_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('title', models.CharField(max_length=200, verbose_name='Title (English)')),
                ('title_kinyarwanda', models.CharField(blank=True, default='', max_length=200, verbose_name='Title (Kinyarwanda)')),
                ('description', models.TextField(blank=True, default='', verbose_name='Description (English)')),
                ('description_kinyarwanda', models.TextField(blank=True, default='', verbose_name='Description (Kinyarwanda)')),
                ('open_date', models.DateTimeField(blank=True, help_text='When the quiz unlocks for students. If published but open_date is in future, quiz remains scheduled.', null=True, verbose_name='Open Date')),
                ('deadline', models.DateTimeField(blank=True, help_text='When the quiz closes. Submissions after this date are blocked.', null=True, verbose_name='Deadline / Due Date')),
                ('time_limit_minutes', models.PositiveSmallIntegerField(default=0, help_text='0 indicates no time limit.', verbose_name='Time Limit (minutes)')),
                ('total_score', models.PositiveIntegerField(default=100, help_text='Total maximum achievable points for this quiz.', verbose_name='Total Score / Points')),
                ('passing_score', models.PositiveIntegerField(default=70, help_text='Passing threshold percentage (e.g. 70%).', verbose_name='Passing Score (%)')),
                ('rubric', models.TextField(blank=True, default='', help_text='Comprehensive grading rubric, evaluation criteria, and instructions for students.', verbose_name='Grading Rubric & Guidelines (English)')),
                ('rubric_kinyarwanda', models.TextField(blank=True, default='', verbose_name='Grading Rubric & Guidelines (Kinyarwanda)')),
                ('max_attempts', models.PositiveSmallIntegerField(default=1, help_text='Number of attempts permitted (0 for unlimited).', verbose_name='Maximum Attempts')),
                ('shuffle_questions', models.BooleanField(default=False, verbose_name='Shuffle Questions')),
                ('is_published', models.BooleanField(db_index=True, default=False, verbose_name='Published')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='lms.course', verbose_name='Course')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_quizzes', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('module', models.ForeignKey(blank=True, help_text='Optional: link quiz directly to a specific module within the course.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='lms.module', verbose_name='Module')),
            ],
            options={
                'verbose_name': 'Quiz',
                'verbose_name_plural': 'Quizzes',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='QuizQuestionItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('sort_order', models.PositiveIntegerField(db_index=True, default=0, help_text='Controls the display ordering of this record within its parent. Lower values appear first.', verbose_name='Sort Order')),
                ('points', models.PositiveSmallIntegerField(default=1, verbose_name='Points / Weight')),
                ('question_text', models.TextField(verbose_name='Question (English)')),
                ('question_text_kinyarwanda', models.TextField(blank=True, default='', verbose_name='Question (Kinyarwanda)')),
                ('option_a', models.CharField(max_length=500, verbose_name='Option A (English)')),
                ('option_b', models.CharField(max_length=500, verbose_name='Option B (English)')),
                ('option_c', models.CharField(blank=True, default='', max_length=500, verbose_name='Option C (English)')),
                ('option_d', models.CharField(blank=True, default='', max_length=500, verbose_name='Option D (English)')),
                ('option_a_kinyarwanda', models.CharField(blank=True, default='', max_length=500, verbose_name='Option A (Kinyarwanda)')),
                ('option_b_kinyarwanda', models.CharField(blank=True, default='', max_length=500, verbose_name='Option B (Kinyarwanda)')),
                ('option_c_kinyarwanda', models.CharField(blank=True, default='', max_length=500, verbose_name='Option C (Kinyarwanda)')),
                ('option_d_kinyarwanda', models.CharField(blank=True, default='', max_length=500, verbose_name='Option D (Kinyarwanda)')),
                ('correct_option', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], default='A', max_length=1, verbose_name='Correct Option')),
                ('explanation', models.TextField(blank=True, default='', verbose_name='Explanation (English)')),
                ('explanation_kinyarwanda', models.TextField(blank=True, default='', verbose_name='Explanation (Kinyarwanda)')),
                ('domain', models.CharField(choices=[('PRIORITY', 'Priority Rules & Intersections'), ('SIGNAGE', 'Traffic Signage & Road Markings'), ('SPEED', 'Speed Limits & Overtaking'), ('LEGAL', 'Legal Framework & Penalties'), ('SAFETY', 'Vehicle Safety & First Aid'), ('PARKING', 'Parking & Stopping Rules')], db_index=True, default='PRIORITY', max_length=20, verbose_name='Domain')),
                ('difficulty', models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], db_index=True, default='MEDIUM', max_length=10, verbose_name='Difficulty')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('original_question', models.ForeignKey(blank=True, help_text='Reference to the bank question this was pulled from, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quiz_instances', to='lms.quizquestion', verbose_name='Source Bank Question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='lms.quiz', verbose_name='Quiz')),
            ],
            options={
                'verbose_name': 'Quiz Question Item',
                'verbose_name_plural': 'Quiz Question Items',
                'ordering': ['sort_order', '-created_at'],
                'abstract': False,
            },
        ),
    ]
