# Generated by Django 5.1.1 on 2026-09-30 15:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0005_quiz_quizquestionitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HelpTicket',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('recipient_role', models.CharField(choices=[('TUTOR', 'Tutor / Instructor'), ('TECH_SUPPORT', 'Technical Support Team')], default='TUTOR', max_length=20, verbose_name='Addressed To')),
                ('category', models.CharField(choices=[('CONTENT_INQUIRY', 'Course Content / Lesson Inquiry'), ('TECHNICAL_ISSUE', 'Technical / Platform Bug'), ('EXAM_DISPUTE', 'Mock Exam / Grade Question'), ('ACCOUNT_BILLING', 'Account / Payment Issue'), ('OTHER', 'Other Inquiry')], default='CONTENT_INQUIRY', max_length=30, verbose_name='Category')),
                ('subject', models.CharField(max_length=200, verbose_name='Subject')),
                ('message', models.TextField(verbose_name='Message / Details')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='MEDIUM', max_length=20, verbose_name='Priority')),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('IN_PROGRESS', 'In Progress'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed')], db_index=True, default='OPEN', max_length=20, verbose_name='Status')),
                ('response', models.TextField(blank=True, default='', verbose_name='Resolution Response / Reply')),
                ('resolved_at', models.DateTimeField(blank=True, null=True, verbose_name='Resolved At')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Staff/Tutor')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='help_tickets', to=settings.AUTH_USER_MODEL, verbose_name='Requester')),
            ],
            options={
                'verbose_name': 'Help Ticket',
                'verbose_name_plural': 'Help Tickets',
                'ordering': ['-created_at'],
            },
        ),
    ]
