# Generated by Django 5.1.1 on 2026-10-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lms', '0006_helpticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='is_student_only',
            field=models.BooleanField(db_index=True, default=False, help_text='If True, this module is only available to registered students and staff. Guests cannot view this module.', verbose_name='Student Only'),
        ),
    ]
