# Generated by Django 5.1.1 on 2026-09-10 14:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPrice',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('category', models.CharField(choices=[('A', 'Category A (Motorcycle / Pikipiki)'), ('B', 'Category B (Light Passenger Vehicle / Ikinyabiziga gisanzwe)'), ('C', 'Category C (Heavy Goods Vehicle / Truck / Ikamyo)'), ('D', 'Category D (Passenger Bus / Bisi)'), ('E', 'Category E (Trailer / Remorque)'), ('F', 'Category F (Specially Adapted / Special)')], db_index=True, max_length=5, unique=True, verbose_name='License Category')),
                ('price_rwf', models.PositiveIntegerField(help_text='Booking service fee in Rwandan Francs (RWF)', verbose_name='Price (RWF)')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
            ],
            options={
                'verbose_name': 'Category Price',
                'verbose_name_plural': 'Category Prices',
                'ordering': ['category'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PartnerTeacher',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone_number', models.CharField(db_index=True, max_length=25, verbose_name='Phone Number')),
                ('driving_school_affiliation', models.CharField(blank=True, help_text='e.g. Inyange Driving School or Independent Instructor', max_length=150, verbose_name='Affiliated Driving School')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('notes', models.TextField(blank=True, verbose_name='Internal Notes')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
            ],
            options={
                'verbose_name': 'Partner Driving Teacher',
                'verbose_name_plural': 'Partner Driving Teachers',
                'ordering': ['first_name', 'last_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BookingApplication',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('ticket_number', models.CharField(db_index=True, editable=False, max_length=30, unique=True, verbose_name='Ticket Number')),
                ('first_name', models.CharField(max_length=100, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=100, verbose_name='Last Name')),
                ('phone_number', models.CharField(db_index=True, max_length=25, verbose_name='Phone Number')),
                ('national_id_encrypted', models.TextField(help_text='AES-256 encrypted 16-digit Rwandan National ID', verbose_name='National ID (Encrypted)')),
                ('national_id_hash', models.CharField(blank=True, db_index=True, help_text='HMAC-SHA256 hash for deduplication/lookup without decrypting', max_length=64, verbose_name='National ID Blind Index')),
                ('date_of_birth', models.DateField(verbose_name='Date of Birth')),
                ('license_category', models.CharField(choices=[('A', 'Category A (Motorcycle / Pikipiki)'), ('B', 'Category B (Light Passenger Vehicle / Ikinyabiziga gisanzwe)'), ('C', 'Category C (Heavy Goods Vehicle / Truck / Ikamyo)'), ('D', 'Category D (Passenger Bus / Bisi)'), ('E', 'Category E (Trailer / Remorque)'), ('F', 'Category F (Specially Adapted / Special)')], db_index=True, max_length=5, verbose_name='License Category')),
                ('preferred_district', models.CharField(choices=[('GASABO', 'Gasabo'), ('KICUKIRO', 'Kicukiro'), ('NYARUGENGE', 'Nyarugenge'), ('BURERA', 'Burera'), ('GAKENKE', 'Gakenke'), ('GICUMBI', 'Gicumbi'), ('MUSANZE', 'Musanze'), ('RULINDO', 'Rulindo'), ('GISAGARA', 'Gisagara'), ('HUYE', 'Huye'), ('KAMONYI', 'Kamonyi'), ('MUHANGA', 'Muhanga'), ('NYAMAGABE', 'Nyamagabe'), ('NYANZA', 'Nyanza'), ('NYARUGURU', 'Nyaruguru'), ('RUHANGO', 'Ruhango'), ('BUGESERA', 'Bugesera'), ('GATSIBO', 'Gatsibo'), ('KAYONZA', 'Kayonza'), ('KIREHE', 'Kirehe'), ('NGOMA', 'Ngoma'), ('NYAGATARE', 'Nyagatare'), ('RWAMAGANA', 'Rwamagana'), ('KARONGI', 'Karongi'), ('NGORORERO', 'Ngororero'), ('NYABIHU', 'Nyabihu'), ('NYAMASHEKE', 'Nyamasheke'), ('RUBAVU', 'Rubavu'), ('RUSIZI', 'Rusizi'), ('RUTSIRO', 'Rutsiro')], db_index=True, max_length=50, verbose_name='Preferred District')),
                ('working_site', models.CharField(blank=True, choices=[('BUSANZA AUTOMATED CENTER', 'BUSANZA AUTOMATED CENTER'), ('BUSANZA SITE (KIC)', 'BUSANZA SITE (KIC)')], help_text="MANDATORY if preferred district is Kicukiro ('BUSANZA AUTOMATED CENTER' or 'BUSANZA SITE (KIC)')", max_length=50, null=True, verbose_name='Working Site')),
                ('price_rwf', models.PositiveIntegerField(help_text='Service price recorded at the time of booking', verbose_name='Price (RWF)')),
                ('state', models.CharField(choices=[('PENDING', 'Pending — Submitted to System Admin'), ('PROCESSING', 'Processing — Agent Actively Booking Slot'), ('COMPLETED', 'Completed — Slot Successfully Booked'), ('SLOTS_UNAVAILABLE', 'Slots Unavailable — Retained in Queue'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=30, verbose_name='State')),
                ('irembo_billing_number', models.CharField(blank=True, db_index=True, help_text='Attached by admin upon successfully booking the slot on Irembo', max_length=100, verbose_name='Irembo Billing Number')),
                ('irembo_application_number', models.CharField(blank=True, max_length=100, verbose_name='Irembo Application Number')),
                ('confirmed_test_date', models.DateField(blank=True, null=True, verbose_name='Confirmed Test Date')),
                ('confirmed_test_time', models.TimeField(blank=True, null=True, verbose_name='Confirmed Test Time')),
                ('confirmed_venue', models.CharField(blank=True, max_length=255, verbose_name='Confirmed Venue')),
                ('confirmation_pdf', models.FileField(blank=True, null=True, upload_to='bookings/confirmations/%Y/%m/', verbose_name='Confirmation PDF')),
                ('agent_notes', models.TextField(blank=True, verbose_name='Agent / Admin Notes')),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Submitted At')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completed At')),
                ('applicant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_applications', to=settings.AUTH_USER_MODEL, verbose_name='Applicant User')),
                ('assigned_agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL, verbose_name='Assigned Admin/Agent')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('partner_teacher', models.ForeignKey(blank=True, help_text='Private instructor who taught the student (optional)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='student_bookings', to='booking.partnerteacher', verbose_name='Partner Driving Teacher')),
            ],
            options={
                'verbose_name': 'Booking Application',
                'verbose_name_plural': 'Booking Applications',
                'ordering': ['-submitted_at'],
                'abstract': False,
                'indexes': [models.Index(fields=['applicant', 'state', '-submitted_at'], name='bk_app_state_idx'), models.Index(fields=['license_category', 'state'], name='bk_cat_state_idx'), models.Index(fields=['preferred_district', 'state'], name='bk_dist_state_idx')],
            },
        ),
    ]
