# Generated by Django 5.1.1 on 2026-09-10 14:13

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('action', models.CharField(choices=[('NID_ACCESS', 'National ID Accessed'), ('NID_WRITE', 'National ID Written'), ('NID_PURGE', 'National ID Purged'), ('USER_REGISTERED', 'User Registered'), ('USER_VERIFIED', 'Phone Number Verified'), ('USER_SUSPENDED', 'User Suspended'), ('USER_REACTIVATED', 'User Reactivated'), ('ROLE_CHANGE', 'User Role Changed'), ('GUEST_UPGRADED', 'Guest Upgraded to Student'), ('PASSWORD_RESET', 'Password Reset'), ('ADMIN_LOGIN', 'Admin Login'), ('ADMIN_LOGOUT', 'Admin Logout'), ('CONSENT_TOS', 'Terms of Service Accepted'), ('CONSENT_PRIVACY', 'Privacy Policy Accepted'), ('EXAM_STARTED', 'Exam Session Started'), ('EXAM_SUBMITTED', 'Exam Session Submitted'), ('EXAM_FLAGGED', 'Exam Session Flagged'), ('EXAM_CERTIFIED', 'Exam Grade Certified'), ('EXAM_REJECTED', 'Exam Grade Rejected'), ('SNAPSHOT_CAPTURED', 'Proctoring Snapshot Captured'), ('SNAPSHOT_PURGE', 'Proctoring Snapshots Purged'), ('BOOKING_CREATED', 'Booking Order Created'), ('BOOKING_ACCESSED', 'Booking Record Accessed'), ('BOOKING_STATE', 'Booking State Changed'), ('BOOKING_LOCKED', 'Booking Locked by Agent'), ('BOOKING_CONFIRMED', 'Booking Slot Confirmed'), ('BOOKING_EXHAUSTED', 'Booking Slots Exhausted'), ('BOOKING_REFUNDED', 'Booking Refunded'), ('PAYMENT_INITIATED', 'Payment Initiated'), ('PAYMENT_SUCCESS', 'Payment Succeeded'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('CONTENT_PUBLISHED', 'Course Content Published'), ('CONTENT_DELETED', 'Course Content Deleted'), ('QUESTION_CREATED', 'Question Bank Entry Created'), ('PII_EXPORT', 'PII Data Exported'), ('DATA_RETENTION_RUN', 'Data Retention Policy Executed'), ('INTEGRITY_CHECK', 'Audit Log Integrity Checked'), ('SYSTEM_CONFIG', 'System Configuration Changed')], db_index=True, max_length=30, verbose_name='Action')),
                ('severity', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], db_index=True, default='LOW', max_length=10, verbose_name='Severity')),
                ('performed_by_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Performed By (User ID)')),
                ('performed_by_phone', models.CharField(blank=True, help_text='Only the last 4 digits are stored for privacy.', max_length=10, verbose_name='Performed By (Phone — last 4 digits)')),
                ('target_user_id', models.UUIDField(blank=True, db_index=True, null=True, verbose_name='Target User ID')),
                ('object_type', models.CharField(blank=True, help_text="Model class name of the affected record. E.g. 'BookingOrder'.", max_length=100, verbose_name='Object Type')),
                ('object_id', models.CharField(blank=True, db_index=True, help_text='UUID or identifier of the affected record.', max_length=64, verbose_name='Object ID')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP Address')),
                ('user_agent', models.TextField(blank=True, verbose_name='User Agent')),
                ('request_id', models.CharField(blank=True, db_index=True, help_text='X-Request-ID header value for distributed tracing.', max_length=64, verbose_name='Request ID')),
                ('http_method', models.CharField(blank=True, max_length=10, verbose_name='HTTP Method')),
                ('endpoint', models.CharField(blank=True, max_length=300, verbose_name='Endpoint')),
                ('context', models.JSONField(blank=True, default=dict, help_text='Structured key-value context for this event. No raw PII allowed.', verbose_name='Context')),
                ('record_hash', models.CharField(blank=True, help_text='SHA-256 of the canonical record content. Mismatch during verification indicates DB-level tampering.', max_length=64, verbose_name='Record Hash')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Timestamp')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
                'default_permissions': ('view',),
                'indexes': [models.Index(fields=['action', 'severity', 'timestamp'], name='audit_audit_action_cf2dd7_idx'), models.Index(fields=['performed_by_id', 'timestamp'], name='audit_audit_perform_7618d5_idx'), models.Index(fields=['target_user_id', 'timestamp'], name='audit_audit_target__5a55d0_idx'), models.Index(fields=['object_type', 'object_id'], name='audit_audit_object__1f9df3_idx')],
            },
        ),
    ]
