# Generated by Django 5.1.1 on 2026-09-10 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamSession',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('track', models.CharField(choices=[('B2C', 'Personal (Remote)'), ('B2B', 'Enterprise Lab')], default='B2C', max_length=5, verbose_name='Track')),
                ('status', models.CharField(choices=[('PENDING', 'Pending Pre-flight'), ('ACTIVE', 'In Progress'), ('SUBMITTED', 'Submitted — Awaiting Review'), ('GRADED', 'Graded — Board Certified'), ('FLAGGED', 'Flagged — Integrity Violation'), ('EXPIRED', 'Expired — Time Limit Exceeded')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Started At')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='Submitted At')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expires At')),
                ('score', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Score')),
                ('total_questions', models.PositiveSmallIntegerField(default=20, verbose_name='Total Questions')),
                ('passed', models.BooleanField(blank=True, null=True, verbose_name='Passed')),
                ('device_fingerprint', models.CharField(blank=True, max_length=200, verbose_name='Device Fingerprint')),
                ('violation_count', models.PositiveSmallIntegerField(default=0, verbose_name='Violation Count')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exam_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Exam Session',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProctoringEvent',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('event_type', models.CharField(choices=[('SNAPSHOT', 'Scheduled Webcam Snapshot'), ('ANOMALY_SNAPSHOT', 'Anomaly-Triggered Snapshot'), ('WINDOW_BLUR', 'Window Lost Focus'), ('TAB_SWITCH', 'Tab Switch Detected'), ('FULLSCREEN_EXIT', 'Fullscreen Exited'), ('MOBILE_BLOCKED', 'Mobile Device Blocked'), ('SESSION_START', 'Session Started'), ('SESSION_END', 'Session Ended')], db_index=True, max_length=30, verbose_name='Event Type')),
                ('snapshot_image', models.ImageField(blank=True, null=True, upload_to='proctoring/snapshots/%Y/%m/', verbose_name='Snapshot')),
                ('metadata', models.JSONField(blank=True, default=dict, verbose_name='Metadata')),
                ('is_violation', models.BooleanField(db_index=True, default=False, verbose_name='Is Violation')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_events', to='examinations.examsession')),
            ],
            options={
                'verbose_name': 'Proctoring Event',
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('selected_option', models.CharField(blank=True, default='', max_length=1, verbose_name='Selected Option')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='Correct')),
                ('answered_at', models.DateTimeField(blank=True, null=True, verbose_name='Answered At')),
                ('sequence_number', models.PositiveSmallIntegerField(default=0, verbose_name='Sequence')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='session_appearances', to='lms.quizquestion')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_questions', to='examinations.examsession')),
            ],
            options={
                'ordering': ['sequence_number'],
                'abstract': False,
                'unique_together': {('session', 'sequence_number')},
            },
        ),
    ]
