# Generated by Django 5.1.1 on 2026-09-13 06:31

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0001_initial'),
        ('live_classes', '0003_alter_cohort_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='examsession',
            name='approval_notes',
            field=models.TextField(blank=True, default='', verbose_name='System Approval Notes'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Approved At'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='approved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_approved_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Approved By'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='board_decision',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Board Decision'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='board_notes',
            field=models.TextField(blank=True, default='', verbose_name='Board Review Notes'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='board_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Board Reviewed At'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='board_reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='board_reviewed_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Board Reviewer'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='exam_sessions', to='live_classes.cohort', verbose_name='Enrolled Cohort'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='is_published',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Is Published'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='published_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Published At'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='published_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Published By'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='training_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='training_reviewed_sessions', to=settings.AUTH_USER_MODEL, verbose_name='Training Administrator'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='training_decision',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='Training Decision'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='training_notes',
            field=models.TextField(blank=True, default='', verbose_name='Training Review Notes'),
        ),
        migrations.AddField(
            model_name='examsession',
            name='training_reviewed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Training Reviewed At'),
        ),
        migrations.AlterField(
            model_name='examsession',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending Pre-flight'), ('ACTIVE', 'In Progress'), ('SUBMITTED', 'Submitted — Awaiting Board Review'), ('BOARD_REVIEW', 'Under Board Review'), ('TRAINING_REVIEW', 'Under Training Admin Review'), ('SYSTEM_REVIEW', 'Awaiting System Admin Approval'), ('APPROVED', 'Approved — Certificate Auto-Generated'), ('PUBLISHED', 'Published — Official Results Released'), ('FLAGGED', 'Flagged — Integrity Violation'), ('REJECTED', 'Rejected'), ('EXPIRED', 'Expired — Time Limit Exceeded')], db_index=True, default='PENDING', max_length=25, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Certificate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('certificate_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Certificate Serial Number')),
                ('student_name', models.CharField(max_length=200, verbose_name='Student Full Name')),
                ('student_code', models.CharField(blank=True, max_length=100, verbose_name='Student Code / National ID')),
                ('track_type', models.CharField(choices=[('STUDENT', 'Student Enrolled (Cohort Theory Accreditation)'), ('GUEST', 'Guest Diagnostic (Provisional Readiness Assessment)'), ('ENTERPRISE', 'Enterprise Driving School (B2B Certified Lab)')], db_index=True, default='STUDENT', max_length=20, verbose_name='Track Type')),
                ('enterprise_name', models.CharField(blank=True, default='', help_text='Mentioned explicitly on Enterprise B2B certificates.', max_length=255, verbose_name='Partner Driving School Name')),
                ('started_at', models.DateTimeField(blank=True, help_text='Displayed for enrolled students and enterprise, omitted for guests.', null=True, verbose_name='Curriculum Start Date')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Completion / Exam Date')),
                ('score', models.PositiveSmallIntegerField(verbose_name='Score Achieved')),
                ('total_questions', models.PositiveSmallIntegerField(default=20, verbose_name='Total Questions')),
                ('passing_score', models.PositiveSmallIntegerField(default=12, verbose_name='Passing Score Threshold')),
                ('passed', models.BooleanField(default=True, verbose_name='Passed Status')),
                ('issue_date', models.DateField(auto_now_add=True, verbose_name='Issue Date')),
                ('verification_hash', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256 Verification Hash')),
                ('verification_url', models.CharField(max_length=500, verbose_name='Verification URL')),
                ('template_snapshot', models.JSONField(blank=True, default=dict, help_text='Preserves signatories, wording, and logo at issuance time.', verbose_name='Template Snapshot')),
                ('is_valid', models.BooleanField(default=True, verbose_name='Is Valid')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('exam_session', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='certificate', to='examinations.examsession', verbose_name='Exam Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificates', to=settings.AUTH_USER_MODEL, verbose_name='Student')),
            ],
            options={
                'verbose_name': 'Certificate',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CertificateTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('template_type', models.CharField(choices=[('STUDENT', 'Student Enrolled (Cohort Theory Accreditation)'), ('GUEST', 'Guest Diagnostic (Provisional Readiness Assessment)'), ('ENTERPRISE', 'Enterprise Driving School (B2B Certified Lab)')], db_index=True, max_length=20, unique=True, verbose_name='Template Category')),
                ('title', models.CharField(default='Certificate of Theory Competence', max_length=255, verbose_name='Certificate Title')),
                ('course_name', models.CharField(default='Rwanda Driving Theory — Provisional License Preparation', max_length=255, verbose_name='Course Name')),
                ('declaration_text', models.TextField(default='This is to certify that {student_name} has successfully completed the Rwanda Driving Theory Curriculum and demonstrated proficiency in Traffic Regulations, Road Signage, and Highway Code Safety with a certified score of {score}/{total_questions}.', verbose_name='Declaration Text')),
                ('confirmation_notes', models.TextField(default='Certified in accordance with Rwanda National Police traffic theory regulations and Rwanda Law No 058/2021 on Personal Data Protection. Scan the embedded QR code to verify authenticity.', verbose_name='Confirmation & Accreditation Notes')),
                ('logo_url', models.CharField(blank=True, default='/assets/logo.svg', max_length=500, verbose_name='Sifo Drive Logo URL / Asset')),
                ('training_admin_name', models.CharField(default='Training Directorate', max_length=150, verbose_name='Training Administrator Name')),
                ('training_admin_title', models.CharField(default='Head of Training & Pedagogy', max_length=150, verbose_name='Training Administrator Title')),
                ('training_admin_signature', models.TextField(blank=True, default='', verbose_name='Training Admin Signature (Base64 / URL)')),
                ('director_name', models.CharField(default='Sifo Platform Director', max_length=150, verbose_name='Sifo Director Name')),
                ('director_title', models.CharField(default='Managing Director, Sifo Drive', max_length=150, verbose_name='Sifo Director Title')),
                ('director_signature', models.TextField(blank=True, default='', verbose_name='Director Signature (Base64 / URL)')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
            ],
            options={
                'verbose_name': 'Certificate Template',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
    ]
