# Generated by Django 5.1.1 on 2026-09-13 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('examinations', '0002_examsession_approval_notes_examsession_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificatetemplate',
            name='conferral_text',
            field=models.CharField(default='This official credential is proudly awarded to', max_length=255, verbose_name='Conferral Lead-in Text'),
        ),
        migrations.AddField(
            model_name='certificatetemplate',
            name='header_subtitle',
            field=models.CharField(default='Republic of Rwanda • Sifo Drive Theory Accreditation', max_length=255, verbose_name='Authority Header / Subtitle'),
        ),
    ]
