# Generated by Django 5.1.1 on 2026-09-10 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('recipient_phone', models.CharField(blank=True, db_index=True, help_text='E.164 phone number e.g. +250781234567', max_length=25, verbose_name='Recipient Phone')),
                ('recipient_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Recipient Email')),
                ('notification_type', models.CharField(choices=[('OTP', 'OTP Verification Code'), ('WELCOME', 'Welcome to Sifo Drive'), ('GUEST_UPGRADE', 'Guest Upgraded to Student'), ('PAYMENT_SUCCESS', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('BOOKING_QUEUED', 'Irembo Slot Queued'), ('BOOKING_CONFIRMED', 'Irembo Slot Confirmed'), ('BOOKING_SLOTS_EXHAUSTED', 'Irembo Slots Exhausted'), ('BOOKING_REMINDER', 'Physical Exam Reminder'), ('EXAM_RESULT', 'Practice Exam Result'), ('LIVE_CLASS_SCHEDULED', 'Live Class Scheduled'), ('LIVE_CLASS_REMINDER', 'Live Class Starting Soon'), ('COURSE_PROGRESS', 'Course Milestone Reached'), ('SECURITY_ALERT', 'Security Alert'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('GENERAL', 'General Notification')], db_index=True, default='GENERAL', max_length=40, verbose_name='Type')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('IN_APP', 'In-App Notification'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], db_index=True, default='IN_APP', max_length=20, verbose_name='Channel')),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20, verbose_name='Priority')),
                ('title', models.CharField(max_length=255, verbose_name='Title (EN)')),
                ('title_rw', models.CharField(blank=True, help_text='Kinyarwanda title', max_length=255, verbose_name='Title (RW)')),
                ('body', models.TextField(verbose_name='Body (EN)')),
                ('body_rw', models.TextField(blank=True, help_text='Kinyarwanda body', verbose_name='Body (RW)')),
                ('action_url', models.CharField(blank=True, help_text='Frontend client route or deep link e.g. /courses/module-1 or /exams/result/123', max_length=500, verbose_name='Action URL')),
                ('is_read', models.BooleanField(db_index=True, default=False, verbose_name='Is Read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='Read At')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued in Worker'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('READ', 'Read'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Context data: exam_id, booking_id, amount_rwf, transaction_id, etc.', verbose_name='Metadata')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('recipient', models.ForeignKey(blank=True, help_text='Recipient user. Can be null for guest phone-only OTPs before account creation.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('sms_enabled', models.BooleanField(default=True, help_text='Receive SMS alerts for important account and exam events.', verbose_name='SMS Notifications Enabled')),
                ('in_app_enabled', models.BooleanField(default=True, verbose_name='In-App Notifications Enabled')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='Email Notifications Enabled')),
                ('exam_alerts', models.BooleanField(default=True, verbose_name='Exam Alerts Enabled')),
                ('booking_alerts', models.BooleanField(default=True, verbose_name='Irembo Booking Alerts Enabled')),
                ('promo_alerts', models.BooleanField(default=False, verbose_name='Promotional / Marketing Alerts Enabled')),
                ('preferred_language', models.CharField(choices=[('rw', 'Kinyarwanda'), ('en', 'English'), ('fr', 'French')], default='rw', max_length=10, verbose_name='Preferred Language')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('template_code', models.CharField(db_index=True, help_text='Unique identifier, e.g. OTP_VERIFICATION, PAYMENT_SUCCESS, IREMBO_CONFIRMED', max_length=80, unique=True, verbose_name='Template Code')),
                ('notification_type', models.CharField(choices=[('OTP', 'OTP Verification Code'), ('WELCOME', 'Welcome to Sifo Drive'), ('GUEST_UPGRADE', 'Guest Upgraded to Student'), ('PAYMENT_SUCCESS', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('BOOKING_QUEUED', 'Irembo Slot Queued'), ('BOOKING_CONFIRMED', 'Irembo Slot Confirmed'), ('BOOKING_SLOTS_EXHAUSTED', 'Irembo Slots Exhausted'), ('BOOKING_REMINDER', 'Physical Exam Reminder'), ('EXAM_RESULT', 'Practice Exam Result'), ('LIVE_CLASS_SCHEDULED', 'Live Class Scheduled'), ('LIVE_CLASS_REMINDER', 'Live Class Starting Soon'), ('COURSE_PROGRESS', 'Course Milestone Reached'), ('SECURITY_ALERT', 'Security Alert'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('GENERAL', 'General Notification')], db_index=True, max_length=40, verbose_name='Notification Type')),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('IN_APP', 'In-App Notification'), ('EMAIL', 'Email'), ('PUSH', 'Push Notification')], default='SMS', max_length=20, verbose_name='Channel')),
                ('language', models.CharField(choices=[('rw', 'Kinyarwanda'), ('en', 'English'), ('fr', 'French')], default='rw', max_length=10, verbose_name='Language')),
                ('title_template', models.CharField(blank=True, help_text="Template for title, e.g. 'Sifo Drive: Kwemeza Konti'", max_length=255, verbose_name='Title Template')),
                ('body_template', models.TextField(help_text="Template body with variables in {variable_name} format.\nExample: 'Muraho {name}, kode yawe yo kwiyandikisha muri Sifo Drive ni {otp}. Irangira mu minota {expiry}.'", verbose_name='Body Template')),
                ('is_active', models.BooleanField(default=True, verbose_name='Is Active')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='Description')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'ordering': ['template_code', 'language'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SMSNotification',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Server-side timestamp of record creation.', verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, help_text='Server-side timestamp of last modification.', verbose_name='Updated At')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique UUID4 identifier. Generated automatically.', primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(db_index=True, default=False, verbose_name='Is Deleted')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('recipient_phone', models.CharField(db_index=True, max_length=25, verbose_name='Recipient Phone')),
                ('message_type', models.CharField(choices=[('OTP', 'OTP Verification Code'), ('WELCOME', 'Welcome to Sifo Drive'), ('GUEST_UPGRADE', 'Guest Upgraded to Student'), ('PAYMENT_SUCCESS', 'Payment Received'), ('PAYMENT_FAILED', 'Payment Failed'), ('PAYMENT_REFUNDED', 'Payment Refunded'), ('BOOKING_QUEUED', 'Irembo Slot Queued'), ('BOOKING_CONFIRMED', 'Irembo Slot Confirmed'), ('BOOKING_SLOTS_EXHAUSTED', 'Irembo Slots Exhausted'), ('BOOKING_REMINDER', 'Physical Exam Reminder'), ('EXAM_RESULT', 'Practice Exam Result'), ('LIVE_CLASS_SCHEDULED', 'Live Class Scheduled'), ('LIVE_CLASS_REMINDER', 'Live Class Starting Soon'), ('COURSE_PROGRESS', 'Course Milestone Reached'), ('SECURITY_ALERT', 'Security Alert'), ('SYSTEM_ANNOUNCEMENT', 'System Announcement'), ('GENERAL', 'General Notification')], db_index=True, default='OTP', max_length=40, verbose_name='Type')),
                ('message_body', models.TextField(verbose_name='Message Body')),
                ('sender_id', models.CharField(default='SIFO_DRIVE', max_length=30, verbose_name='Sender ID')),
                ('provider', models.CharField(default='CONSOLE_MOCK', help_text='Gateway used: PINDO, AFRICAS_TALKING, HTTP_GATEWAY, CONSOLE_MOCK', max_length=50, verbose_name='SMS Provider')),
                ('provider_message_id', models.CharField(blank=True, db_index=True, max_length=150, verbose_name='Provider Message ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('SENT', 'Sent'), ('DELIVERED', 'Delivered'), ('FAILED', 'Failed')], db_index=True, default='PENDING', max_length=20, verbose_name='Status')),
                ('retry_count', models.PositiveSmallIntegerField(default=0, verbose_name='Retry Count')),
                ('error_message', models.TextField(blank=True, verbose_name='Error Message')),
                ('provider_response', models.JSONField(blank=True, null=True, verbose_name='Provider Response')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Sent At')),
                ('delivered_at', models.DateTimeField(blank=True, null=True, verbose_name='Delivered At')),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_deletions', to=settings.AUTH_USER_MODEL, verbose_name='Deleted By')),
                ('notification', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sms_logs', to='notifications.notification', verbose_name='Parent Notification')),
            ],
            options={
                'verbose_name': 'SMS Notification Log',
                'verbose_name_plural': 'SMS Notification Logs',
                'ordering': ['-created_at'],
                'abstract': False,
            },
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['recipient', 'is_read', '-created_at'], name='notif_recipient_read_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['notification_type', '-created_at'], name='notif_type_created_idx'),
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['recipient_phone', '-created_at'], name='sms_phone_created_idx'),
        ),
        migrations.AddIndex(
            model_name='smsnotification',
            index=models.Index(fields=['status', '-created_at'], name='sms_status_created_idx'),
        ),
    ]
